export const GAME_IDS = [
  {
    title: 'A Plague Tale',
    gamePassId: '9ND0CG3LM22K',
    howLongToBeatId: '65080',
    metaCriticId: 'a-plague-tale-innocence',
  },
  {
    title: 'Age of Empires Definitive Edition',
    gamePassId: '9NJWTJSVGVLJ',
    howLongToBeatId: '68260',
    metaCriticId: 'age-of-empires-ii-definitive-edition',
  },
  {
    title: 'Age of Empires II',
    gamePassId: '9NJDD0JGPP2Q',
    howLongToBeatId: '12193',
    metaCriticId: 'age-of-empires-ii-the-age-of-kings',
  },
  {
    title: 'Age of Empires III',
    gamePassId: '9N1HF804QXN4',
    howLongToBeatId: '270',
    metaCriticId: 'age-of-empires-iii',
  },
  {
    title: 'Alan Wake',
    gamePassId: '9NKV44QF1R68',
    howLongToBeatId: '319',
    metaCriticId: 'alan-wake',
  },
  {
    title: 'Alien',
    gamePassId: '9NSRJ872SGH7',
    howLongToBeatId: '22425',
    metaCriticId: 'aliens-versus-predator-2',
  },
  {
    title: 'Alvastia Chronicles',
    gamePassId: '9MVJGBNNFPPS',
    howLongToBeatId: '67659',
    metaCriticId: 'alvastia-chronicles',
  },
  {
    title: 'Among Us',
    gamePassId: '9NG07QJNK38J',
    howLongToBeatId: '74207',
    metaCriticId: 'the-wolf-among-us-episode-1---faith',
  },
  {
    title: 'Ape Out',
    gamePassId: '9NR6DZ9F76P8',
    howLongToBeatId: '56938',
    metaCriticId: 'ape-out',
  },
  {
    title: 'ARK: Survival Evolved',
    gamePassId: '9MT8ND8BS6NB',
    howLongToBeatId: '26629',
    metaCriticId: 'ark-survival-evolved',
  },
  {
    title: 'Astrologaster',
    gamePassId: '9NFT0CMC62DX',
    howLongToBeatId: '67977',
    metaCriticId: 'astrologaster',
  },
  {
    title: 'ASTRONEER',
    gamePassId: '9NBLGGH43KZB',
    howLongToBeatId: '42182',
    metaCriticId: 'astroneer',
  },
  {
    title: 'Battle Chasers',
    gamePassId: '9NT8XR7D5L00',
    howLongToBeatId: '30017',
    metaCriticId: 'battle-chasers-nightwar',
  },
  {
    title: 'Battlefleet Gothic',
    gamePassId: '9NGWKW55M85P',
    howLongToBeatId: '64475',
    metaCriticId: 'battlefleet-gothic-armada',
  },
  {
    title: 'BATTLETECH',
    gamePassId: '9NQVDQS2BC10',
    howLongToBeatId: '55977',
    metaCriticId: 'battletech',
  },
  {
    title: 'Battletoads',
    gamePassId: '9N7GCF5SGCXC',
    howLongToBeatId: '80699',
    metaCriticId: 'battletoads',
  },
  {
    title: 'Blair Witch',
    gamePassId: '9NG7LG421V0Q',
    howLongToBeatId: '68319',
    metaCriticId: 'blair-witch-volume-i-rustin-parr',
  },
  {
    title: 'Bleeding Edge',
    gamePassId: '9NX6XGVJ0J3D',
    howLongToBeatId: '68093',
    metaCriticId: 'bleeding-edge',
  },
  {
    title: 'Bloodstained: Ritual of the Night',
    gamePassId: '9MWB2BFF0SPD',
    howLongToBeatId: '26266',
    metaCriticId: 'bloodstained-ritual-of-the-night',
  },
  {
    title: 'Bridge Constructor Portal',
    gamePassId: '9PDXF172R7VJ',
    howLongToBeatId: '51365',
    metaCriticId: 'bridge-constructor-portal',
  },
  {
    title: 'Broforce',
    gamePassId: '9P03ZQMBMV65',
    howLongToBeatId: '17638',
    metaCriticId: 'broforce',
  },
  {
    title: 'Call of the Sea',
    gamePassId: '9NNG78K7N91K',
    howLongToBeatId: '77918',
    metaCriticId: 'call-of-the-sea',
  },
  {
    title: 'Carrion',
    gamePassId: '9MSMJH3C6TKR',
    howLongToBeatId: '68169',
    metaCriticId: 'carrion',
  },
  {
    title: 'Carto',
    gamePassId: '9PFS8Q01C2C4',
    howLongToBeatId: '80570',
    metaCriticId: 'cartoon-network-universe-fusionfall',
  },
  {
    title: 'Celeste',
    gamePassId: 'BWMQL2RPWBHB',
    howLongToBeatId: '42818',
    metaCriticId: 'celeste',
  },
  {
    title: 'Children of Morta',
    gamePassId: '9P675WH90SB4',
    howLongToBeatId: '22534',
    metaCriticId: 'children-of-morta',
  },
  {
    title: 'Cities',
    gamePassId: '9NWVC7XP3PFD',
    howLongToBeatId: '24640',
    metaCriticId: 'cities-skylines',
  },
  {
    title: 'Clustertruck',
    gamePassId: '9N8WVMD7J5GQ',
    howLongToBeatId: '40215',
    metaCriticId: 'clustertruck',
  },
  {
    title: 'Comanche',
    gamePassId: '9N2H2GRB4D0K',
    howLongToBeatId: '72601',
    metaCriticId: 'enemy-engaged-rah-66-comanche-versus-ka-52-hokum',
  },
  {
    title: 'Company of Heroes 2',
    gamePassId: '9NX9WH5F0RZD',
    howLongToBeatId: '1875',
    metaCriticId: 'company-of-heroes-2-ardennes-assault',
  },
  {
    title: 'Control ',
    gamePassId: '9PL1J8PJKH29',
    howLongToBeatId: '57507',
    metaCriticId: 'star-control-3',
  },
  {
    title: 'Crackdown 3',
    gamePassId: '9NXR6469DM2P',
    howLongToBeatId: '38828',
    metaCriticId: 'crackdown-3',
  },
  {
    title: 'CrossCode',
    gamePassId: '9NFDPQ0KZ6RN',
    howLongToBeatId: '24970',
    metaCriticId: 'crosscode',
  },
  {
    title: 'Crossing Souls',
    gamePassId: '9PD1Z95CNTW4',
    howLongToBeatId: '25103',
    metaCriticId: 'crossing-souls',
  },
  {
    title: 'Crusader Kings III',
    gamePassId: '9N7GG222GTTH',
    howLongToBeatId: '71763',
    metaCriticId: 'crusader-kings-iii',
  },
  {
    title: 'Cyber Shadow',
    gamePassId: '9NX9LJ5JSWH8',
    howLongToBeatId: '42816',
    metaCriticId: 'cyber-shadow',
  },
  {
    title: 'Darksiders Genesis',
    gamePassId: '9NJ5X04M30HN',
    howLongToBeatId: '68043',
    metaCriticId: 'darksiders-genesis',
  },
  {
    title: 'Day of the Tentacle Remastered',
    gamePassId: '9NKK6CX54183',
    howLongToBeatId: '35880',
    metaCriticId: 'day-of-the-tentacle-remastered',
  },
  {
    title: 'Dead by Daylight ',
    gamePassId: '9NMS4SFNBGBH',
    howLongToBeatId: '37986',
    metaCriticId: 'dead-by-daylight',
  },
  {
    title: 'Dead Cells',
    gamePassId: '9NKVX66J0ZSK',
    howLongToBeatId: '45727',
    metaCriticId: 'dead-cells',
  },
  {
    title: 'Deep Rock Galactic',
    gamePassId: '9NHFVWX1V7QJ',
    howLongToBeatId: '47169',
    metaCriticId: 'deep-rock-galactic',
  },
  {
    title: 'Deliver Us The Moon',
    gamePassId: '9PF6BS5DGNLX',
    howLongToBeatId: '71372',
    metaCriticId: 'deliver-us-the-moon',
  },
  {
    title: 'Descenders',
    gamePassId: 'C37XBX7DCBZ0',
    howLongToBeatId: '55598',
    metaCriticId: 'descenders',
  },
  {
    title: 'Desperados III',
    gamePassId: '9P1ZX74WPL68',
    howLongToBeatId: '60291',
    metaCriticId: 'desperados-iii',
  },
  {
    title: 'Disgaea 4 Complete',
    gamePassId: '9PFJDSL1CC7G',
    howLongToBeatId: '71701',
    metaCriticId: 'disgaea-4-complete+',
  },
  {
    title: 'Dishonored 2',
    gamePassId: '9MW4RJDRSF78',
    howLongToBeatId: '26731',
    metaCriticId: 'dishonored-2',
  },
  {
    title: 'Disneyland Adventures',
    gamePassId: '9N6Z8DQXSQWH',
    howLongToBeatId: '4994',
    metaCriticId: 'disneyland-adventures',
  },
  {
    title: "Don't Starve",
    gamePassId: 'C0XBNVR137DZ',
    howLongToBeatId: '2675',
    metaCriticId: 'dont-starve-together',
  },
  {
    title: 'Donut County',
    gamePassId: '9N6V2181GHLM',
    howLongToBeatId: '51323',
    metaCriticId: 'donut-county',
  },
  {
    title: 'DOOM Eternal ',
    gamePassId: '9PK09BL31FK1',
    howLongToBeatId: '57506',
    metaCriticId: 'doom-eternal',
  },
  {
    title: 'Double Kick Heroes',
    gamePassId: '9NJPT63K27W8',
    howLongToBeatId: '53061',
    metaCriticId: 'double-kick-heroes',
  },
  {
    title: 'Downwell',
    gamePassId: '9P641Z19NT2S',
    howLongToBeatId: '31178',
    metaCriticId: 'downwell',
  },
  {
    title: 'DRAGON QUEST XI S',
    gamePassId: '9PBDC0XZ8TXK',
    howLongToBeatId: '69743',
    metaCriticId:
      'dragon-quest-xi-s-echoes-of-an-elusive-age---definitive-edition',
  },
  {
    title: 'Drake Hollow',
    gamePassId: '9PGNGGWBX1NR',
    howLongToBeatId: '82637',
    metaCriticId: 'drake-hollow',
  },
  {
    title: 'Dungeon of the Endless',
    gamePassId: '9N46K0X6TBZK',
    howLongToBeatId: '17454',
    metaCriticId: 'dungeon-of-the-endless',
  },
  {
    title: 'Eastshade',
    gamePassId: '9PLCR0FR564K',
    howLongToBeatId: '65001',
    metaCriticId: 'eastshade',
  },
  {
    title: 'Endless Legend',
    gamePassId: '9NP09BFQNHCJ',
    howLongToBeatId: '18226',
    metaCriticId: 'endless-legend',
  },
  {
    title: 'Endless Space 2',
    gamePassId: '9NV3Q7WVN2RB',
    howLongToBeatId: '41360',
    metaCriticId: 'endless-space-2',
  },
  {
    title: 'Enter The Gungeon',
    gamePassId: '9NB65S6LFZRT',
    howLongToBeatId: '35549',
    metaCriticId: 'enter-the-gungeon',
  },
  {
    title: 'Europa Universalis IV',
    gamePassId: '9PHQJWGLTZM8',
    howLongToBeatId: '13304',
    metaCriticId: 'europa-universalis-iv',
  },
  {
    title: 'F1 2019',
    gamePassId: '9NL9VGSH00LL',
    howLongToBeatId: '68644',
    metaCriticId: 'f1-2019',
  },
  {
    title: 'Fallout 76 ',
    gamePassId: '9NKGNMNK3K3Z',
    howLongToBeatId: '57416',
    metaCriticId: 'fallout-76-wastelanders',
  },
  {
    title: 'FINAL FANTASY IX',
    gamePassId: '9NPGTNQFC8B5',
    howLongToBeatId: '3505',
    metaCriticId: 'final-fantasy-ix',
  },
  {
    title: 'FINAL FANTASY VII ',
    gamePassId: '9PN0W216SKZB',
    howLongToBeatId: '3521',
    metaCriticId: 'final-fantasy-viii-remastered',
  },
  {
    title: 'FINAL FANTASY VIII Remastered ',
    gamePassId: '9P35DPLN1JCN',
    howLongToBeatId: '3524',
    metaCriticId: 'final-fantasy-viii-remastered',
  },
  {
    title: "Five Nights at Freddy's",
    gamePassId: '9N5253J559LR',
    howLongToBeatId: '20811',
    metaCriticId: 'five-nights-at-freddys',
  },
  {
    title: "Five Nights at Freddy's 2",
    gamePassId: '9NBR2ZSD99FX',
    howLongToBeatId: '22612',
    metaCriticId: 'five-nights-at-freddys-2',
  },
  {
    title: "Five Nights at Freddy's 3",
    gamePassId: '9P6N7LQ4HZFD',
    howLongToBeatId: '24456',
    metaCriticId: 'five-nights-at-freddys',
  },
  {
    title: "Five Nights at Freddy's 4",
    gamePassId: '9PLDLMPLR7JV',
    howLongToBeatId: '28975',
    metaCriticId: 'five-nights-at-freddys-4',
  },
  {
    title: "Five Nights at Freddy's",
    gamePassId: '9PJ2DSSXZR0P',
    howLongToBeatId: '20811',
    metaCriticId: 'five-nights-at-freddys',
  },
  {
    title: 'For The King',
    gamePassId: '9NS1CD1V4BKW',
    howLongToBeatId: '45024',
    metaCriticId: 'age-of-empires-ii-the-age-of-kings',
  },
  {
    title: 'Forager',
    gamePassId: '9P5SFDNW6V13',
    howLongToBeatId: '62412',
    metaCriticId: 'forager',
  },
  {
    title: 'Forza Horizon 4 ',
    gamePassId: '9PNJXVCVWD4K',
    howLongToBeatId: '55661',
    metaCriticId: 'forza-horizon-4',
  },
  {
    title: 'Forza Motorsport 7 ',
    gamePassId: '9N3NK5WW05HT',
    howLongToBeatId: '46400',
    metaCriticId: 'forza-motorsport-7',
  },
  {
    title: 'Frostpunk',
    gamePassId: '9NS0KH25D76X',
    howLongToBeatId: '41585',
    metaCriticId: 'frostpunk',
  },
  {
    title: 'Full Throttle Remastered',
    gamePassId: '9P3ZRGNQVC7D',
    howLongToBeatId: '44400',
    metaCriticId: 'full-throttle-remastered',
  },
  {
    title: 'Gato Roboto',
    gamePassId: '9PBJQ90CT236',
    howLongToBeatId: '67569',
    metaCriticId: 'gato-roboto',
  },
  {
    title: 'Gears 5',
    gamePassId: 'C2KDNLT2H7DM',
    howLongToBeatId: '57422',
    metaCriticId: 'gears-5',
  },
  {
    title: 'Gears 5 ',
    gamePassId: '9P4KMR76PLLQ',
    howLongToBeatId: '57422',
    metaCriticId: 'gears-5',
  },
  {
    title: 'Gears of War 4',
    gamePassId: '9NBLGGH4PBBM',
    howLongToBeatId: '26788',
    metaCriticId: 'gears-of-war-4',
  },
  {
    title: 'Gears of War',
    gamePassId: '9NBLGGH3SHM5',
    howLongToBeatId: '3862',
    metaCriticId: 'gears-of-war',
  },
  {
    title: 'Gears Tactics',
    gamePassId: '9NN3HCKW5TPC',
    howLongToBeatId: '57740',
    metaCriticId: 'gears-tactics',
  },
  {
    title: 'Ghost of a Tale',
    gamePassId: '9PJR5XZG5CNS',
    howLongToBeatId: '21687',
    metaCriticId: 'ghost-of-a-tale',
  },
  {
    title: 'Goat Simulator ',
    gamePassId: '9MXWKHJ3VZZH',
    howLongToBeatId: '17536',
    metaCriticId: 'goat-simulator',
  },
  {
    title: 'Golf With Your Friends',
    gamePassId: '9MVK5W0HMRP7',
    howLongToBeatId: '34956',
    metaCriticId: 'golf-with-your-friends',
  },
  { title: 'GONNER2 ', gamePassId: '9P44W70MC99Z', howLongToBeatId: '84332' },
  {
    title: 'GreedFall',
    gamePassId: '9PB79JST8PDH',
    howLongToBeatId: '62519',
    metaCriticId: 'greedfall',
  },
  {
    title: 'Grim Fandango Remastered',
    gamePassId: '9PC288TN7R8K',
    howLongToBeatId: '23473',
    metaCriticId: 'grim-fandango-remastered',
  },
  {
    title: 'Grounded',
    gamePassId: '9PJTHRNVH62H',
    howLongToBeatId: '77857',
    metaCriticId: 'grounded',
  },
  {
    title: 'Guacamelee! 2',
    gamePassId: '9NVK1W7L093S',
    howLongToBeatId: '59509',
    metaCriticId: 'guacamelee!-2',
  },
  {
    title: 'Halo 2',
    gamePassId: '9P5739G419LD',
    howLongToBeatId: '4262',
    metaCriticId: 'halo-2',
  },
  {
    title: 'Halo 3',
    gamePassId: '9PGL2Z1H9M4R',
    howLongToBeatId: '4263',
    metaCriticId: 'halo-the-master-chief-collection---halo-3-odst',
  },
  {
    title: 'Halo 3',
    gamePassId: '9P6VZCRGXFMX',
    howLongToBeatId: '4263',
    metaCriticId: 'halo-the-master-chief-collection---halo-3-odst',
  },
  {
    title: 'Halo 4',
    gamePassId: '9P8CFXZH93CK',
    howLongToBeatId: '4265',
    metaCriticId: 'halo-the-master-chief-collection---halo-4',
  },
  {
    title: 'Halo Wars 2',
    gamePassId: '9NBLGGH5WMKM',
    howLongToBeatId: '37985',
    metaCriticId: 'halo-wars-2',
  },
  {
    title: 'Halo Wars 2',
    gamePassId: '9NBLGGH515BD',
    howLongToBeatId: '37985',
    metaCriticId: 'halo-wars-2',
  },
  {
    title: 'Halo Wars',
    gamePassId: '9NBLGGH5WLR0',
    howLongToBeatId: '4267',
    metaCriticId: 'halo-wars-2',
  },
  {
    title: 'Halo',
    gamePassId: '9NWQMVSB63N4',
    howLongToBeatId: '22621',
    metaCriticId: 'halo-the-master-chief-collection---halo-3-odst',
  },
  {
    title: 'Halo',
    gamePassId: '9N9WZT3PJ27W',
    howLongToBeatId: '22621',
    metaCriticId: 'halo-the-master-chief-collection---halo-3-odst',
  },
  {
    title: 'Halo',
    gamePassId: '9WZDNCRFHWFH',
    howLongToBeatId: '22621',
    metaCriticId: 'halo-the-master-chief-collection---halo-3-odst',
  },
  {
    title: 'Halo',
    gamePassId: '9WZDNCRFJBFJ',
    howLongToBeatId: '22621',
    metaCriticId: 'halo-the-master-chief-collection---halo-3-odst',
  },
  {
    title: 'Halo',
    gamePassId: '9NTM9HXNLSZX',
    howLongToBeatId: '22621',
    metaCriticId: 'halo-the-master-chief-collection---halo-3-odst',
  },
  {
    title: 'Haven',
    gamePassId: '9NZL91Q08XRV',
    howLongToBeatId: '80569',
    metaCriticId: 'haven',
  },
  {
    title: 'Hearts of Iron IV',
    gamePassId: '9NF6WPNS1S73',
    howLongToBeatId: '37795',
    metaCriticId: 'hearts-of-iron-iv',
  },
  {
    title: 'Heave Ho',
    gamePassId: '9P8JHRDVBLHB',
    howLongToBeatId: '70193',
    metaCriticId: 'heave-ho',
  },
  {
    title: 'Hellblade',
    gamePassId: '9NCLP4LV5K7Z',
    howLongToBeatId: '41638',
    metaCriticId: 'hellblade-senuas-sacrifice-vr-edition',
  },
  {
    title: 'Hello Neighbor',
    gamePassId: '9NDDH3R9DF40',
    howLongToBeatId: '40794',
    metaCriticId: 'hello-neighbor',
  },
  {
    title: 'Hollow Knight',
    gamePassId: '9PKM22F7C9K5',
    howLongToBeatId: '26286',
    metaCriticId: 'hollow-knight',
  },
  {
    title: 'Hotline Miami',
    gamePassId: '9PPCS86WS28Z',
    howLongToBeatId: '4530',
    metaCriticId: 'hotline-miami',
  },
  {
    title: 'Human Fall Flat',
    gamePassId: '9MT4HS1CP72W',
    howLongToBeatId: '38887',
    metaCriticId: 'human-fall-flat',
  },
  {
    title: 'HyperDot',
    gamePassId: '9NVVJ8TBD7KP',
    howLongToBeatId: '77188',
    metaCriticId: 'hyperdot',
  },
  {
    title: 'Hypnospace Outlaw',
    gamePassId: '9PM3NVB3PXG0',
    howLongToBeatId: '65593',
    metaCriticId: 'hypnospace-outlaw',
  },
  {
    title: 'Ikenfell',
    gamePassId: '9N2X1J99S4M9',
    howLongToBeatId: '80165',
    metaCriticId: 'ikenfell',
  },
  {
    title: 'Injustice 2',
    gamePassId: '9PHT4W7WBBDQ',
    howLongToBeatId: '37862',
    metaCriticId: 'injustice-2',
  },
  {
    title: 'It Lurks Below',
    gamePassId: '9PFW68JLS81F',
    howLongToBeatId: '56403',
    metaCriticId: 'it-lurks-below',
  },
  {
    title: 'Katana Zero',
    gamePassId: '9P6CVNVMK56R',
    howLongToBeatId: '33020',
    metaCriticId: 'katana-zero',
  },
  {
    title: 'Kathy Rain',
    gamePassId: '9P8HN2T2SZGB',
    howLongToBeatId: '36847',
    metaCriticId: 'kathy-rain',
  },
  {
    title: 'Killer Instinct',
    gamePassId: '9NBLGGH51BMC',
    howLongToBeatId: '14350',
    metaCriticId: 'killer-instinct',
  },
  {
    title: 'Knights and Bikes',
    gamePassId: '9P64KV1HQK07',
    howLongToBeatId: '67984',
    metaCriticId: 'knights-and-bikes',
  },
  {
    title: 'Levelhead',
    gamePassId: '9PJZBB8FWK8H',
    howLongToBeatId: '76093',
    metaCriticId: 'levelhead',
  },
  {
    title: 'Lonely Mountains',
    gamePassId: '9MV6MCVLT8GR',
    howLongToBeatId: '71406',
    metaCriticId: 'lonely-mountains-downhill',
  },
  {
    title: 'Machinarium',
    gamePassId: '9N83GKZLC8BK',
    howLongToBeatId: '5478',
    metaCriticId: 'machinarium',
  },
  {
    title: 'MARVEL VS. CAPCOM',
    gamePassId: '9PGSCB1X2P7G',
    howLongToBeatId: '10779',
    metaCriticId: 'marvel-vs-capcom-infinite',
  },
  {
    title: 'MechWarrior 5',
    gamePassId: '9PB86W3JK8Z5',
    howLongToBeatId: '67949',
    metaCriticId: 'mechwarrior-5-mercenaries',
  },
  {
    title: 'Microsoft Flight Simulator',
    gamePassId: '9NXN8GF8N9HT',
    howLongToBeatId: '70960',
    metaCriticId: 'microsoft-flight-simulator',
  },
  {
    title: 'Middle-earth',
    gamePassId: '9PDV8FKWP3B4',
    howLongToBeatId: '44022',
    metaCriticId: 'the-lord-of-the-rings-the-battle-for-middle-earth-ii',
  },
  {
    title: 'Minecraft Dungeons',
    gamePassId: '9P8MK4NC0LJB',
    howLongToBeatId: '68149',
    metaCriticId: 'minecraft-dungeons',
  },
  {
    title: 'MISTOVER',
    gamePassId: '9P8K66J3CQ9S',
    howLongToBeatId: '71153',
    metaCriticId: 'mistover',
  },
  {
    title: 'Momodora',
    gamePassId: '9NZL00LF4V58',
    howLongToBeatId: '35555',
    metaCriticId: 'momodora-reverie-under-the-moonlight',
  },
  {
    title: 'Monster Sanctuary',
    gamePassId: '9PBWWQGXVMKC',
    howLongToBeatId: '70012',
    metaCriticId: 'monster-sanctuary',
  },
  {
    title: 'Monster Train',
    gamePassId: '9NP4BGBLLLXM',
    howLongToBeatId: '78633',
    metaCriticId: 'monster-train',
  },
  {
    title: 'Moonlighter',
    gamePassId: '9P8XJRLCLH2P',
    howLongToBeatId: '56787',
    metaCriticId: 'moonlighter',
  },
  {
    title: 'Morkredd',
    gamePassId: '9PKD7RG0TQP4',
    howLongToBeatId: '85965',
    metaCriticId: 'morkredd',
  },
  {
    title: 'Mother Russia Bleeds',
    gamePassId: '9NVFHBKDLPM4',
    howLongToBeatId: '22543',
    metaCriticId: 'mother-russia-bleeds',
  },
  {
    title: 'MotoGP 20',
    gamePassId: '9N88HSBP6RJ8',
    howLongToBeatId: '77737',
    metaCriticId: 'motogp-20',
  },
  {
    title: 'Mount & Blade',
    gamePassId: '9PFZC53PVTDB',
    howLongToBeatId: '6243',
    metaCriticId: 'mount-blade-warband---napoleonic-wars',
  },
  {
    title: 'Moving Out',
    gamePassId: '9N9H593X8SVP',
    howLongToBeatId: '75031',
    metaCriticId: 'moving-out',
  },
  {
    title: 'My Time At Portia',
    gamePassId: '9NBLSN1JP7TH',
    howLongToBeatId: '52787',
    metaCriticId: 'my-time-at-portia',
  },
  {
    title: 'Neon Abyss',
    gamePassId: '9PLWSGHFQ4PS',
    howLongToBeatId: '77366',
    metaCriticId: 'neon-abyss',
  },
  {
    title: 'Neoverse',
    gamePassId: '9NNSTP6KJTZ9',
    howLongToBeatId: '68733',
    metaCriticId: 'neoverse',
  },
  {
    title: "New Super Lucky's Tale",
    gamePassId: '9MZN3SMXN824',
    howLongToBeatId: '71552',
    metaCriticId: 'new-super-luckys-tale',
  },
  {
    title: 'Night Call',
    gamePassId: '9N5KSQG0R9TB',
    howLongToBeatId: '69216',
    metaCriticId: 'night-call',
  },
  {
    title: 'Night in the Woods ',
    gamePassId: '9MV13BTTCKLL',
    howLongToBeatId: '20078',
    metaCriticId: 'night-in-the-woods',
  },
  {
    title: "No Man's Sky",
    gamePassId: 'BQVQTL3PCH05',
    howLongToBeatId: '20074',
    metaCriticId: 'no-mans-sky',
  },
  {
    title: 'Nowhere Prophet',
    gamePassId: '9P01NRSZCVR6',
    howLongToBeatId: '69248',
    metaCriticId: 'nowhere-prophet',
  },
  {
    title: 'Observation',
    gamePassId: '9PBLH1322GX0',
    howLongToBeatId: '67287',
    metaCriticId: 'observation',
  },
  {
    title: 'Ori and the Blind Forest',
    gamePassId: '9NBLGGH1Z6FB',
    howLongToBeatId: '19265',
    metaCriticId: 'ori-and-the-blind-forest',
  },
  {
    title: 'Ori and the Will of the Wisps',
    gamePassId: '9N8CD0XZKLP4',
    howLongToBeatId: '46428',
    metaCriticId: 'ori-and-the-will-of-the-wisps',
  },
  {
    title: 'Out of the Park Baseball 21',
    gamePassId: '9NNW9V8DVPG6',
    howLongToBeatId: '80631',
    metaCriticId: 'out-of-the-park-baseball-21',
  },
  {
    title: 'Overcooked! 2',
    gamePassId: '9PGB72NFG5JN',
    howLongToBeatId: '57518',
    metaCriticId: 'overcooked!-2',
  },
  {
    title: 'Oxenfree',
    gamePassId: '9NBLGGH6CTZ5',
    howLongToBeatId: '33620',
    metaCriticId: 'oxenfree',
  },
  {
    title: 'Pandemic',
    gamePassId: '9P8Q4W21QQZ2',
    howLongToBeatId: '47069',
    metaCriticId: 'grave-mania-pandemic-pandemonium',
  },
  {
    title: 'Phoenix Point',
    gamePassId: '9P1P5Q3BNM7J',
    howLongToBeatId: '53702',
    metaCriticId: 'phoenix-point',
  },
  {
    title: 'Pikuniku ',
    gamePassId: '9N8QNKN5ZKTH',
    howLongToBeatId: '64060',
    metaCriticId: 'pikuniku',
  },
  {
    title: 'Pillars of Eternity',
    gamePassId: '9P5LZC1KB48V',
    howLongToBeatId: '13434',
    metaCriticId: 'pillars-of-eternity',
  },
  {
    title: 'Plebby Quest',
    gamePassId: '9MWBPSQ5PKQR',
    howLongToBeatId: '78632',
    metaCriticId: 'plebby-quest-the-crusades',
  },
  {
    title: 'Power Rangers',
    gamePassId: '9P5VMG8D4P4B',
    howLongToBeatId: '65929',
    metaCriticId: 'power-rangers-ninja-storm',
  },
  {
    title: 'Prison Architect',
    gamePassId: '9P5S2J2VLLPR',
    howLongToBeatId: '7308',
    metaCriticId: 'prison-architect',
  },
  {
    title: 'Project Winter',
    gamePassId: '9P3SX4G50LZ1',
    howLongToBeatId: '68128',
    metaCriticId: 'project-winter',
  },
  {
    title: 'RAGE 2',
    gamePassId: '9P2J7WHV0K4N',
    howLongToBeatId: '58031',
    metaCriticId: 'god-eater-2-rage-burst',
  },
  {
    title: 'ReCore',
    gamePassId: '9NBLGGH1Z6FQ',
    howLongToBeatId: '26789',
    metaCriticId: 'recore',
  },
  {
    title: 'RESIDENT EVIL 7 biohazard',
    gamePassId: '9NBLGGH4SPK6',
    howLongToBeatId: '38051',
    metaCriticId: 'resident-evil-7-biohazard',
  },
  {
    title: 'Rise of Nations',
    gamePassId: '9NS84HCWZD8B',
    howLongToBeatId: '7832',
    metaCriticId: 'rise-of-nations',
  },
  {
    title: 'River City Girls',
    gamePassId: '9PGNT102001S',
    howLongToBeatId: '69993',
    metaCriticId: 'river-city-girls',
  },
  {
    title: 'Rush',
    gamePassId: '9P3PL76N0KWZ',
    howLongToBeatId: '8029',
    metaCriticId: 'simcity-4-rush-hour',
  },
  {
    title: 'ScourgeBringer',
    gamePassId: '9NXPV1T3WS34',
    howLongToBeatId: '68579',
    metaCriticId: 'scourgebringer',
  },
  {
    title: 'Sea of Thieves',
    gamePassId: '9P2N57MC619K',
    howLongToBeatId: '38053',
    metaCriticId: 'sea-of-thieves',
  },
  {
    title: 'Shadow Warrior 2',
    gamePassId: '9P6SFBR1TCWQ',
    howLongToBeatId: '39740',
    metaCriticId: 'shadow-warrior-2',
  },
  {
    title: 'Slay The Spire',
    gamePassId: '9MZQR8317S3B',
    howLongToBeatId: '51390',
    metaCriticId: 'slay-the-spire',
  },
  {
    title: 'Spiritfarer',
    gamePassId: '9NG5L58FD3X5',
    howLongToBeatId: '68189',
    metaCriticId: 'spiritfarer',
  },
  {
    title: 'Star Renegades',
    gamePassId: '9PK5S1QKV10D',
    howLongToBeatId: '71955',
    metaCriticId: 'star-renegades',
  },
  {
    title: 'Starbound',
    gamePassId: '9MTSBWPWPQVQ',
    howLongToBeatId: '9149',
    metaCriticId: 'starbound',
  },
  {
    title: 'State of Decay 2',
    gamePassId: '9NT4X7P8B9NB',
    howLongToBeatId: '46403',
    metaCriticId: 'state-of-decay-2',
  },
  {
    title: 'Stellaris',
    gamePassId: '9NXQPGMR917R',
    howLongToBeatId: '37186',
    metaCriticId: 'stellaris-synthetic-dawn',
  },
  {
    title: 'Stranger Things 3',
    gamePassId: '9PMDDQ228FQD',
    howLongToBeatId: '68766',
    metaCriticId: 'stranger-things-3-the-game',
  },
  {
    title: 'Streets of Rage 4',
    gamePassId: '9N7H54KNCB9N',
    howLongToBeatId: '76482',
    metaCriticId: 'streets-of-rage-4',
  },
  {
    title: 'Streets of Rogue',
    gamePassId: '9NKRBSZXQ2HM',
    howLongToBeatId: '44813',
    metaCriticId: 'streets-of-rogue',
  },
  {
    title: 'Subnautica',
    gamePassId: 'BX3S1Q5DVHRD',
    howLongToBeatId: '23740',
    metaCriticId: 'subnautica',
  },
  {
    title: 'Sunset Overdrive',
    gamePassId: '9NNLBL0T2Z43',
    howLongToBeatId: '21278',
    metaCriticId: 'sunset-overdrive',
  },
  {
    title: "Super Lucky's Tale",
    gamePassId: '9PLMGFWCFZ9G',
    howLongToBeatId: '46426',
    metaCriticId: 'super-luckys-tale',
  },
  {
    title: 'Surviving Mars',
    gamePassId: '9MXB71Q4VWGJ',
    howLongToBeatId: '45951',
    metaCriticId: 'surviving-mars-green-planet',
  },
  {
    title: 'Tales of Vesperia',
    gamePassId: '9N5QWL08HRTR',
    howLongToBeatId: '9608',
    metaCriticId: 'tales-of-vesperia-definitive-edition',
  },
  {
    title: 'Tell Me Why',
    gamePassId: '9NF83PRZK6K3',
    howLongToBeatId: '71968',
    metaCriticId: 'tell-me-why',
  },
  {
    title: 'Tetris Effect',
    gamePassId: '9PPBVK3TK83M',
    howLongToBeatId: '57523',
    metaCriticId: 'tetris-effect',
  },
  {
    title: "The Bard's Tale",
    gamePassId: '9PN3VDFTB5HZ',
    howLongToBeatId: '9772',
    metaCriticId: 'the-bards-tale-iv-directors-cut',
  },
  {
    title: "The Bard's Tale IV",
    gamePassId: 'C2B4T86TXLRS',
    howLongToBeatId: '69339',
    metaCriticId: 'the-bards-tale-iv-directors-cut',
  },
  {
    title: "The Bard's Tale Trilogy",
    gamePassId: '9MVN4ND41DD3',
    howLongToBeatId: '59950',
    metaCriticId: 'the-bards-tale-trilogy-remaster',
  },
  {
    title: 'The Dark Crystal',
    gamePassId: '9NPWSCWJGHL1',
    howLongToBeatId: '57460',
    metaCriticId: 'the-dark-crystal-age-of-resistance-tactics',
  },
  {
    title: 'The Dark Pictures Anthology',
    gamePassId: '9N3TF0CG8NZB',
    howLongToBeatId: '67361',
    metaCriticId: 'the-dark-pictures-anthology-man-of-medan',
  },
  {
    title: 'The Falconeer',
    gamePassId: '9N8J0T5HCDB9',
    howLongToBeatId: '83463',
    metaCriticId: 'the-falconeer',
  },
  {
    title: 'The Gardens Between',
    gamePassId: '9P4Z4TW66LPV',
    howLongToBeatId: '56088',
    metaCriticId: 'the-gardens-between',
  },
  {
    title: 'The Long Dark',
    gamePassId: '9NFKN56ZBMR0',
    howLongToBeatId: '21471',
    metaCriticId: 'the-long-dark',
  },
  {
    title: 'The Medium',
    gamePassId: '9NFSR96G6K4N',
    howLongToBeatId: '78037',
    metaCriticId: 'the-medium',
  },
  {
    title: 'The Messenger',
    gamePassId: '9NNFBW3NGV9K',
    howLongToBeatId: '60176',
    metaCriticId: 'the-messenger',
  },
  {
    title: 'The Outer Worlds',
    gamePassId: '9MWD2Z8L1FBQ',
    howLongToBeatId: '62935',
    metaCriticId: 'the-outer-worlds',
  },
  {
    title: 'The Surge 2',
    gamePassId: '9NLDM4DGX41G',
    howLongToBeatId: '67880',
    metaCriticId: 'the-surge-2',
  },
  {
    title: 'The Swords of Ditto',
    gamePassId: '9NF2DDV5RTH8',
    howLongToBeatId: '48469',
    metaCriticId: 'the-swords-of-ditto',
  },
  {
    title: 'The Touryst',
    gamePassId: '9N9W1JK1X5QJ',
    howLongToBeatId: '70671',
    metaCriticId: 'the-touryst',
  },
  {
    title: 'The Yakuza Remastered Collection ',
    gamePassId: '9NBTL551XL5N',
    howLongToBeatId: '85918',
    metaCriticId: 'the-yakuza-remastered-collection',
  },
  {
    title: 'Thumper',
    gamePassId: '9PHV10KXLJZT',
    howLongToBeatId: '40500',
    metaCriticId: 'thumper',
  },
  {
    title: 'Torment',
    gamePassId: '9NC0071DJ6XC',
    howLongToBeatId: '7093',
    metaCriticId: 'planescape-torment',
  },
  {
    title: 'Totally Accurate Battle Simulator',
    gamePassId: '9PC4RWP34M2D',
    howLongToBeatId: '52878',
    metaCriticId: 'totally-accurate-battle-simulator',
  },
  {
    title: 'Touhou Luna Nights',
    gamePassId: '9NBLGJQQBHH4',
    howLongToBeatId: '60261',
    metaCriticId: 'touhou-luna-nights',
  },
  {
    title: 'Trailmakers',
    gamePassId: '9NSFGM8J6MBJ',
    howLongToBeatId: '56055',
    metaCriticId: 'trailmakers',
  },
  {
    title: 'Train Sim World 2020',
    gamePassId: '9PMT49X8ZGM2',
    howLongToBeatId: '74885',
    metaCriticId: 'train-sim-world-2020',
  },
  {
    title: 'Two Point Hospital',
    gamePassId: '9N08S5VPC4SX',
    howLongToBeatId: '60043',
    metaCriticId: 'two-point-hospital',
  },
  {
    title: 'UnderMine',
    gamePassId: '9N52CQMFH3BB',
    howLongToBeatId: '69349',
    metaCriticId: 'the-incredibles-rise-of-the-underminer',
  },
  {
    title: 'Unruly Heroes ',
    gamePassId: '9P3SS6K8ZQ57',
    howLongToBeatId: '64458',
    metaCriticId: 'unruly-heroes',
  },
  {
    title: 'Unto The End',
    gamePassId: '9MVJ0W5N2L2Q',
    howLongToBeatId: '49816',
    metaCriticId: 'unto-the-end',
  },
  {
    title: 'VA-11 Hall-A',
    gamePassId: '9P9C1HB78K05',
    howLongToBeatId: '25099',
    metaCriticId: 'va-11-hall-a-cyberpunk-bartender-action',
  },
  {
    title: 'Vambrace',
    gamePassId: '9N171CGFVT1L',
    howLongToBeatId: '67877',
    metaCriticId: 'vambrace-cold-soul',
  },
  {
    title: 'Void Bastards',
    gamePassId: '9PJ1CGLKQSWS',
    howLongToBeatId: '67475',
    metaCriticId: 'void-bastards',
  },
  {
    title: 'Wargroove',
    gamePassId: '9NRPTTJ94PCK',
    howLongToBeatId: '61653',
    metaCriticId: 'wargroove',
  },
  {
    title: 'Wasteland 2',
    gamePassId: 'C521HDXRTS7F',
    howLongToBeatId: '11099',
    metaCriticId: 'wasteland-2-directors-cut',
  },
  {
    title: 'Wasteland 3',
    gamePassId: '9NLT5XR52ZS7',
    howLongToBeatId: '42532',
    metaCriticId: 'wasteland-2-directors-cut',
  },
  {
    title: 'Wasteland Remastered',
    gamePassId: '9NGH1FK0RJGL',
    howLongToBeatId: '74755',
    metaCriticId: 'wasteland-remastered',
  },
  {
    title: 'We Happy Few',
    gamePassId: '9NBLGGH5342P',
    howLongToBeatId: '27102',
    metaCriticId: 'we-happy-few',
  },
  {
    title: 'West of Dead',
    gamePassId: '9NV0540N4JRN',
    howLongToBeatId: '77696',
    metaCriticId: 'west-of-dead',
  },
  {
    title: 'What Remains of Edith Finch',
    gamePassId: 'BSLGLG8P9T01',
    howLongToBeatId: '45392',
    metaCriticId: 'what-remains-of-edith-finch',
  },
  {
    title: "Wilmot's Warehouse ",
    gamePassId: '9NCHVR5KH0RN',
    howLongToBeatId: '50395',
    metaCriticId: 'wilmots-warehouse',
  },
  {
    title: 'Wizard of Legend',
    gamePassId: '9MZH0GG41HL9',
    howLongToBeatId: '26294',
    metaCriticId: 'wizard-of-legend',
  },
  {
    title: 'Wolfenstein',
    gamePassId: '9PHFTS44F99K',
    howLongToBeatId: '11249',
    metaCriticId: 'return-to-castle-wolfenstein-enemy-territory',
  },
  {
    title: 'WORLD OF HORROR',
    gamePassId: '9N1FDTTSS49Z',
    howLongToBeatId: '67201',
    metaCriticId: 'world-of-horror',
  },
  {
    title: 'World War Z',
    gamePassId: '9N015DFDMVK6',
    howLongToBeatId: '64828',
    metaCriticId: 'world-war-z',
  },
  {
    title: 'Worms W.M.D',
    gamePassId: '9NVRZZJ4NG99',
    howLongToBeatId: '39481',
    metaCriticId: 'worms-wmd',
  },
  {
    title: 'Xeno Crisis',
    gamePassId: '9PNBGZTL0Z1S',
    howLongToBeatId: '71596',
    metaCriticId: 'xeno-crisis',
  },
  {
    title: 'Yakuza 0 ',
    gamePassId: '9PD0BJRBLRJM',
    howLongToBeatId: '43056',
    metaCriticId: 'yakuza-0',
  },
  {
    title: 'Yakuza 3 Remastered ',
    gamePassId: '9NC4QMRHCNZK',
    howLongToBeatId: '11423',
    metaCriticId: 'the-yakuza-remastered-collection',
  },
  {
    title: 'Yakuza 4 Remastered ',
    gamePassId: '9NWZTB9JQG9S',
    howLongToBeatId: '11424',
    metaCriticId: 'yakuza-4-remastered',
  },
  {
    title: 'Yakuza 5 Remastered ',
    gamePassId: '9MVX1V7W5SW8',
    howLongToBeatId: '22940',
    metaCriticId: 'yakuza-5-remastered',
  },
  {
    title: 'Yakuza Kiwami 2 ',
    gamePassId: '9MZNFNN3XJ3F',
    howLongToBeatId: '49620',
    metaCriticId: 'yakuza-kiwami-2',
  },
  {
    title: 'Yakuza Kiwami ',
    gamePassId: '9P40SC5DQ9K0',
    howLongToBeatId: '39484',
    metaCriticId: 'yakuza-kiwami-2',
  },
  {
    title: 'Yes, Your Grace',
    gamePassId: '9NX14Q0QZD1T',
    howLongToBeatId: '71500',
    metaCriticId: 'yes-your-grace',
  },
  {
    title: 'YIIK',
    gamePassId: '9P3XR9QN0P4C',
    howLongToBeatId: '63089',
    metaCriticId: 'yiik-a-postmodern-rpg',
  },
  {
    title: 'Yooka-Laylee and the Impossible Lair',
    gamePassId: '9NB1LCQDPPM1',
    howLongToBeatId: '68031',
    metaCriticId: 'yooka-laylee-and-the-impossible-lair',
  },
  {
    title: 'Zoo Tycoon',
    gamePassId: '9PJ06TZX4NMH',
    howLongToBeatId: '14293',
    metaCriticId: 'zoo-tycoon-2-marine-mania',
  },
]
